export const language = {
    PE: 'es',
    MX: 'es',
    CO: 'es',
    AR: 'es',
    ES: 'es',
    US: 'en',
    GB: 'en',
    BR: 'pt',
    FR: 'fr',
    DE: 'de',
    VE: 'es',
    CL: 'es',
    EC: 'es',
    BO: 'es',
    PY: 'es',
    UY: 'es',
    CR: 'es',
    PA: 'es',
    GT: 'es',
    HN: 'es',
    SV: 'es',
    NI: 'es',
    DO: 'es',
    CU: 'es'
};

export const timezone = {
    PE: 'America/Lima',
    MX: 'America/Mexico_City',
    CO: 'America/Bogota',
    AR: 'America/Argentina/Buenos_Aires',
    ES: 'Europe/Madrid',
    US: 'America/New_York',
    GB: 'Europe/London',
    BR: 'America/Sao_Paulo',
    FR: 'Europe/Paris',
    DE: 'Europe/Berlin',
    VE: 'America/Caracas',
    CL: 'America/Santiago',
    EC: 'America/Guayaquil',
    BO: 'America/La_Paz',
    PY: 'America/Asuncion',
    UY: 'America/Montevideo',
    CR: 'America/Costa_Rica',
    PA: 'America/Panama',
    GT: 'America/Guatemala',
    HN: 'America/Tegucigalpa',
    SV: 'America/El_Salvador',
    NI: 'America/Managua',
    DO: 'America/Santo_Domingo',
    CU: 'America/Havana'
}